/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "servos_app.h"
#include "servos_hal.h"
#include <math.h>
#include <stdint.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_servos_init(void);
extern void test_servos_get_servos_pan_angle(void);
extern void test_servos_set_servos_pan_angle(void);
extern void test_servos_get_servos_tilt_angle(void);
extern void test_servos_set_servos_tilt_angle(void);
extern void test_servos_point_to_angles(void);
extern void test_servos_pan_angle_to_timervalue(void);
extern void test_servos_tilt_angle_to_timervalue(void);


/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/test_servos.c");
  RUN_TEST(test_servos_init, 27);
  RUN_TEST(test_servos_get_servos_pan_angle, 37);
  RUN_TEST(test_servos_set_servos_pan_angle, 45);
  RUN_TEST(test_servos_get_servos_tilt_angle, 53);
  RUN_TEST(test_servos_set_servos_tilt_angle, 61);
  RUN_TEST(test_servos_point_to_angles, 86);
  RUN_TEST(test_servos_pan_angle_to_timervalue, 119);
  RUN_TEST(test_servos_tilt_angle_to_timervalue, 135);

  return (UnityEnd());
}
