/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "joystick_app.h"
#include "joystick_hal.h"
#include <stdint.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_joystick_init(void);
extern void test_joystick_macros_level(void);
extern void test_joystick_macros_rising(void);
extern void test_joystick_macros_falling(void);


/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/test_joystick.c");
  RUN_TEST(test_joystick_init, 26);
  RUN_TEST(test_joystick_macros_level, 34);
  RUN_TEST(test_joystick_macros_rising, 47);
  RUN_TEST(test_joystick_macros_falling, 77);

  return (UnityEnd());
}
