#ifndef GLOBALS_H
#define GLOBALS_H

#define FONT_HEIGHT 7
#define FONT_WIDTH 5

#define CANVAS_SIZE_PIXEL_Y 50
#define CANVAS_SIZE_PIXEL_X (CANVAS_SIZE_PIXEL_Y*2)

#define TEXT_OFFSET_X 12
#define TEXT_OFFSET_Y 20

/* in ms */
#define SERVOS_STABILIZATION_TIME 1000

/* in ms */
#define LASER_ON_TIME 50

/* in ms */ 
#define FIRST_PIXEL_PAUSE 200
#define VERY_FIRST_PIXEL_PAUSE 500

/* in ms */
#define LASER_SPIRAL_INTERPOINT_DELAY 300

#define USE_SPIRALS (0)

#define NR_OF_SPIRAL_WINDINGS 1

#endif
